export const GET_ELECTRONIC_PRODUCTS_LOAD = "GET_ELECTRONIC_PRODUCTS_LOAD";
export const GET_ELECTRONIC_PRODUCTS_FETCH = "GET_ELECTRONIC_PRODUCTS_FETCH";
export const SET_ELECTORNIC_PRODUCT_CATEGORY_CHANGE =
	"SET_ELECTORNIC_PRODUCT_CATEGORY_CHANGE";
export const RESET_ELECTRONIC_PRODUCTS = "RESET_ELECTRONIC_PRODUCTS";
export const COMPARE_PRODUCT_LOAD = "COMPARE_PRODUCT_LOAD"
export const COMPARE_PRODUCT_FETCH = "COMPARE_PRODUCT_FETCH"
export const PRODUCT_SPECS_LOAD = "PRODUCT_SPECS_LOAD"
export const PRODUCT_SPECS_FETCH = "PRODUCT_SPECS_FETCH"
