export const GET_ELECTRONIC_PRODUCTS_LOAD = "GET_ELECTRONIC_PRODUCTS_LOAD";
export const GET_ELECTRONIC_PRODUCTS_FETCH = "GET_ELECTRONIC_PRODUCTS_FETCH";
export const SET_ELECTORNIC_PRODUCT_CATEGORY_CHANGE =
	"SET_ELECTORNIC_PRODUCT_CATEGORY_CHANGE";
export const RESET_ELECTRONIC_PRODUCTS = "RESET_ELECTRONIC_PRODUCTS";
