export const FILTER_POPUP = "FILTER_POPUP";
export const SORT_POPUP = "SORT_POPUP";
export const SEARCH_SLIDE = "SEARCH_SLIDE";
export const BACK_FROM_PRODUCT_DETAIL = "BACK_FROM_PRODUCT_DETAIL";
export const COMPARE_PRODUCT_SLIDE = "COMPARE_PRODUCT_SLIDE";
export const SET_SIDEBAR = "SET_SIDEBAR";
export const PRODUCT_SPECS_POPUP = "PRODUCT_SPECS_POPUP";
