export const men = {
	topwear: [
		"top-wear",
		"t-shirts",
		"formal-shirts",
		"casual-shirts",
		"winter-wear",
		"sweatshirts",
		"jackets",
		"sweater",
		"raincoats-windcheaters",
	],
	bottomwear: [
		"bottom-wear",
		"jeans",
		"casual-trousers",
		"formal-trousers",
		"track-pants",
		"shorts",
		"cargos",
		"three-fourths",
		"suits-blazers-waistcoats",
		"tracksuits",
	],
	footwear: [
		"mens-footwear",
		"sports-shoes",
		"casual-shoes",
		"formal-shoes",
		"sandals-floaters",
		"flip-flops",
		"loafers",
		"boots",
		"running-shoes",
		"sneakers",
	],
	ethnicwear: ["kurta", "ethnic-sets", "ethnic-pyjama"],
	innerwear: [
		"innerwear-loungewear",
		"briefs-trunks",
		"boxers",
		"pyjamas-and-lounge-pants",
		"night-suits",
	],
	accessories: [
		"ties-socks-caps-more",
		"fastrack",
		"casio",
		"titan",
		"fossil",
		"sonata",
		"backpacks",
		"wallets",
		"belts",
		"sunglasses",
		"luggage-travel",
		"frames",
		"jewellery",
		"skechers",
		"nike",
	],
};

export const women = {
	topwear: [
		"topwear",
		"dresses",
		"party-dresses",
		"winter-wear",
		"sarees",
		"kurtas-kurtis",
		"dress-material",
		"lehenga-choli",
		"blouse",
		"kurta-sets-salwar-suits",
		"gowns",
		"dupattas",
	],
	bottomwear: [
		"jeans",
		"shorts",
		"skirts",
		"jeggings-tights",
		"trousers-capris",
		"leggings-churidars",
		"palazzos",
		"shararas",
		"salwars-patiala",
		"dhoti-pants",
		"ethnic-trousers",
	],
	innerwear: [
		"bras",
		"panties",
		"lingerie-sets",
		"night-dresses-nighties",
		"shapewear",
		"camisoles-slips",
		"lingerie-sleepwear",
		"saree-shapewear-petticoats",
	],
	sportswear: ["swim-beachwear", "sports-wear", "sports-shoes"],
	accessories: [
		"clutches",
		"wallets-belts",
		"luggage-travel",
		"sunglasses",
		"frames",
		"jewellery",
		"silver-jewellery",
		"precious-jewellery",
		"coins-and-bars",
	],
	bags: ["shoulder-bags", "totes", "sling-bags"],
	footwear: [
		"footwear",
		"sandals",
		"flats",
		"heels",
		"wedges",
		"shoes",
		"casual-shoes",
		"boots",
		"ballerinas",
		"slippers-flip-flop's",
	],
};
