const LandingPage = () => {
    return (
        <div>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
            <p>
            epic    
            </p>
        </div>
    )
}
export default LandingPage